version: '3.8'

services:
  # Frontend Next.js app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5002
      - NEXT_PUBLIC_PYTHON_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - node-backend
      - python-backend
    networks:
      - eiendomsmuligheter-network

  # Node.js Express backend
  node-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.node
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - PORT=5002
      - PYTHON_API_URL=http://python-backend:8000
      - JWT_SECRET=eiendomsmuligheter_development_jwt_secret
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_dummy_key}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_dummy_key}
    volumes:
      - ./backend:/app
      - node_backend_node_modules:/app/node_modules
    depends_on:
      - postgres
    networks:
      - eiendomsmuligheter-network

  # Python FastAPI backend
  python-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - PORT=8000
      - HOST=0.0.0.0
      - WORKERS=1
      - RELOAD=true
      - USE_SQLITE=true
      - SECRET_KEY=eiendomsmuligheter_development_key
      - POSTGRES_USER=eiendom_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=eiendomsmuligheter
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_dummy_key}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_dummy_key}
      - KARTVERKET_API_KEY=${KARTVERKET_API_KEY:-dummy_key}
    volumes:
      - ./backend:/app
      - ./static:/app/static
      - python_backend_venv:/app/venv
    depends_on:
      - postgres
    networks:
      - eiendomsmuligheter-network

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=eiendom_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eiendomsmuligheter
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eiendomsmuligheter-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - eiendomsmuligheter-network

volumes:
  postgres-data:
  redis-data:
  frontend_node_modules:
  node_backend_node_modules:
  python_backend_venv:

networks:
  eiendomsmuligheter-network:
    driver: bridge
